<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT6heAul\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT6heAul/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT6heAul.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT6heAul\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerT6heAul\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'T6heAul',
    'container.build_id' => '66f78e84',
    'container.build_time' => 1573089521,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT6heAul');
